services:
  postgres:
    image: postgres
    container_name: postgres_service
    ports:
      - "5432:5432"
    env_file:
      - ./app.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql